services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    user: root
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3001:3001
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data